"""Add matching column to QuestionResult

Revision ID: 3d030f63a384
Revises: 
Create Date: 2024-05-05 00:59:27.614630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d030f63a384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matching', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recived_answer', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_result', schema=None) as batch_op:
        batch_op.drop_column('recived_answer')
        batch_op.drop_column('matching')

    # ### end Alembic commands ###
